/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    articles: Article;
    services: Service;
    testimonials: Testimonial;
    faq: Faq;
    team: Team;
    timeline: Timeline;
    media: Media;
    inquiries: Inquiry;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    faq: FaqSelect<false> | FaqSelect<true>;
    team: TeamSelect<false> | TeamSelect<true>;
    timeline: TimelineSelect<false> | TimelineSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    inquiries: InquiriesSelect<false> | InquiriesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    homepage: Homepage;
    pricing: Pricing;
    coverage: Coverage;
    marketing: Marketing;
    'about-page': AboutPage;
    'contact-page': ContactPage;
    legal: Legal;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    pricing: PricingSelect<false> | PricingSelect<true>;
    coverage: CoverageSelect<false> | CoverageSelect<true>;
    marketing: MarketingSelect<false> | MarketingSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'contact-page': ContactPageSelect<false> | ContactPageSelect<true>;
    legal: LegalSelect<false> | LegalSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role?: ('admin' | 'editor') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  slug: string;
  excerpt?: string | null;
  /**
   * Plain text or HTML body content
   */
  body?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  featuredImage?: (number | null) | Media;
  /**
   * External image URL if not using upload
   */
  imageUrl?: string | null;
  category?: ('Hiring Guide' | 'Pricing' | 'Legal' | 'Maintenance' | 'Interviews' | 'News') | null;
  author?: string | null;
  readTime?: string | null;
  featured?: boolean | null;
  publishedAt?: string | null;
  status?: ('draft' | 'published') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  name: string;
  slug: string;
  description?: string | null;
  icon?: string | null;
  basePrice?: number | null;
  unit?: string | null;
  popular?: boolean | null;
  tag?: string | null;
  tagColor?: string | null;
  image?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  clientName: string;
  initials: string;
  location?: string | null;
  quote: string;
  rating?: number | null;
  colorVariant?: ('primary' | 'secondary' | 'tertiary') | null;
  ownerReply?: string | null;
  featured?: boolean | null;
  order?: number | null;
  avatar?: (number | null) | Media;
  videoUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq".
 */
export interface Faq {
  id: number;
  question: string;
  answer: string;
  pages?: ('home' | 'pricing' | 'how-it-works' | 'general')[] | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team".
 */
export interface Team {
  id: number;
  name: string;
  role: string;
  bio?: string | null;
  photo?: (number | null) | Media;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "timeline".
 */
export interface Timeline {
  id: number;
  year: string;
  title: string;
  description?: string | null;
  image?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries".
 */
export interface Inquiry {
  id: number;
  type: 'match' | 'contact';
  status?: ('new' | 'read' | 'resolved') | null;
  inquiryType?: string | null;
  name?: string | null;
  email?: string | null;
  phone?: string | null;
  service?: string | null;
  neighborhood?: string | null;
  message: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'faq';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'team';
        value: number | Team;
      } | null)
    | ({
        relationTo: 'timeline';
        value: number | Timeline;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'inquiries';
        value: number | Inquiry;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  body?: T;
  content?: T;
  featuredImage?: T;
  imageUrl?: T;
  category?: T;
  author?: T;
  readTime?: T;
  featured?: T;
  publishedAt?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  icon?: T;
  basePrice?: T;
  unit?: T;
  popular?: T;
  tag?: T;
  tagColor?: T;
  image?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  clientName?: T;
  initials?: T;
  location?: T;
  quote?: T;
  rating?: T;
  colorVariant?: T;
  ownerReply?: T;
  featured?: T;
  order?: T;
  avatar?: T;
  videoUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq_select".
 */
export interface FaqSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  pages?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team_select".
 */
export interface TeamSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  bio?: T;
  photo?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "timeline_select".
 */
export interface TimelineSelect<T extends boolean = true> {
  year?: T;
  title?: T;
  description?: T;
  image?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries_select".
 */
export interface InquiriesSelect<T extends boolean = true> {
  type?: T;
  status?: T;
  inquiryType?: T;
  name?: T;
  email?: T;
  phone?: T;
  service?: T;
  neighborhood?: T;
  message?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName?: string | null;
  tagline?: string | null;
  footerBlurb?: string | null;
  phone?: string | null;
  whatsapp?: string | null;
  email?: string | null;
  address?: string | null;
  navItems?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  footerColumns?:
    | {
        title: string;
        links?:
          | {
              label: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  socialLinks?:
    | {
        platform: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  heroEyebrow?: string | null;
  heroHeadline: string;
  heroSubheadline?: string | null;
  heroCtaText?: string | null;
  heroCtaUrl?: string | null;
  heroImage?: string | null;
  stats?:
    | {
        label: string;
        value: string;
        numericTarget?: number | null;
        suffix?: string | null;
        id?: string | null;
      }[]
    | null;
  activityMessages?:
    | {
        message: string;
        id?: string | null;
      }[]
    | null;
  marqueeNeighborhoods?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  marqueeServices?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  aggregateRating?: number | null;
  reviewCount?: number | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing".
 */
export interface Pricing {
  id: number;
  tableRows?:
    | {
        service: string;
        bookingFee: string;
        rate: string;
        id?: string | null;
      }[]
    | null;
  rolePricing?:
    | {
        role: string;
        low: number;
        high: number;
        period?: string | null;
        note?: string | null;
        details?: string | null;
        popular?: boolean | null;
        id?: string | null;
      }[]
    | null;
  feeBreakdown?:
    | {
        label: string;
        value: string;
        type?: ('free' | 'fee' | 'direct') | null;
        id?: string | null;
      }[]
    | null;
  lastUpdated?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coverage".
 */
export interface Coverage {
  id: number;
  /**
   * Set the map center and zoom for your service area. Move the map by adjusting latitude, longitude, and zoom.
   */
  location: {
    /**
     * Label shown on the map (e.g. Greater Nairobi, Mombasa Metro)
     */
    regionLabel?: string | null;
    /**
     * Map center latitude (e.g. Nairobi: -1.2864)
     */
    centerLat: number;
    /**
     * Map center longitude (e.g. Nairobi: 36.8172)
     */
    centerLng: number;
    /**
     * Initial zoom level (8 = wide region, 14 = neighborhood)
     */
    zoom?: number | null;
  };
  section?: {
    eyebrow?: string | null;
    title?: string | null;
    subtitle?: string | null;
  };
  neighborhoods?:
    | {
        name: string;
        workers: number;
        /**
         * Pin latitude (find on Google Maps → right-click → copy coordinates)
         */
        latitude: number;
        /**
         * Pin longitude
         */
        longitude: number;
        popularServices?:
          | {
              service?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  totalWorkers?: number | null;
  avgMatchHours?: number | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "marketing".
 */
export interface Marketing {
  id: number;
  vetting?: {
    title?: string | null;
    passRate?: string | null;
    steps?:
      | {
          icon: string;
          title: string;
          description: string;
          isFinal?: boolean | null;
          id?: string | null;
        }[]
      | null;
  };
  hireSteps?: {
    title?: string | null;
    description?: string | null;
    ctaText?: string | null;
    ctaHref?: string | null;
    steps?:
      | {
          number: string;
          title: string;
          description: string;
          stickyTop?: string | null;
          isFinal?: boolean | null;
          id?: string | null;
        }[]
      | null;
  };
  comparison?: {
    title?: string | null;
    columns?:
      | {
          label: string;
          note: string;
          variant?: ('negative' | 'highlighted') | null;
          id?: string | null;
        }[]
      | null;
  };
  appCta?: {
    title?: string | null;
    description?: string | null;
    appStoreUrl?: string | null;
    playStoreUrl?: string | null;
    image?: string | null;
  };
  matchForm?: {
    title?: string | null;
    description?: string | null;
    benefits?:
      | {
          text?: string | null;
          id?: string | null;
        }[]
      | null;
    serviceOptions?:
      | {
          label?: string | null;
          id?: string | null;
        }[]
      | null;
    successMessage?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  heroTitle?: string | null;
  heroImage?: string | null;
  originStory?: string | null;
  bodyStory?: string | null;
  storyImage?: string | null;
  mission?: string | null;
  vision?: string | null;
  values?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  impactStats?:
    | {
        value: number;
        suffix?: string | null;
        label: string;
        color?: ('primary' | 'secondary' | 'tertiary') | null;
        id?: string | null;
      }[]
    | null;
  ctaTitle?: string | null;
  ctaDescription?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page".
 */
export interface ContactPage {
  id: number;
  heroTitle?: string | null;
  heroDescription?: string | null;
  intents?:
    | {
        id: string;
        icon: string;
        title: string;
        summary?: string | null;
        bestChannel?: ('whatsapp' | 'phone' | 'support' | 'info' | 'form' | 'self-serve') | null;
        responseTime?: string | null;
        actionLabel?: string | null;
        actionHref?: string | null;
        includeWhenContacting?:
          | {
              item?: string | null;
              id?: string | null;
            }[]
          | null;
      }[]
    | null;
  slas?:
    | {
        label: string;
        value: string;
        detail?: string | null;
        id?: string | null;
      }[]
    | null;
  disputeSteps?:
    | {
        step: string;
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  refundRules?:
    | {
        scenario: string;
        outcome: string;
        id?: string | null;
      }[]
    | null;
  inquiryTypes?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  selfServiceLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal".
 */
export interface Legal {
  id: number;
  terms?: {
    updated?: string | null;
    description?: string | null;
    sections?:
      | {
          id: string;
          title: string;
          paragraphs?:
            | {
                paragraph?: string | null;
                id?: string | null;
              }[]
            | null;
          list?:
            | {
                item?: string | null;
                id?: string | null;
              }[]
            | null;
        }[]
      | null;
  };
  privacy?: {
    updated?: string | null;
    description?: string | null;
    sections?:
      | {
          id: string;
          title: string;
          paragraphs?:
            | {
                paragraph?: string | null;
                id?: string | null;
              }[]
            | null;
          list?:
            | {
                item?: string | null;
                id?: string | null;
              }[]
            | null;
        }[]
      | null;
  };
  disclaimer?: {
    updated?: string | null;
    description?: string | null;
    sections?:
      | {
          id: string;
          title: string;
          paragraphs?:
            | {
                paragraph?: string | null;
                id?: string | null;
              }[]
            | null;
          list?:
            | {
                item?: string | null;
                id?: string | null;
              }[]
            | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  footerBlurb?: T;
  phone?: T;
  whatsapp?: T;
  email?: T;
  address?: T;
  navItems?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  footerColumns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  heroEyebrow?: T;
  heroHeadline?: T;
  heroSubheadline?: T;
  heroCtaText?: T;
  heroCtaUrl?: T;
  heroImage?: T;
  stats?:
    | T
    | {
        label?: T;
        value?: T;
        numericTarget?: T;
        suffix?: T;
        id?: T;
      };
  activityMessages?:
    | T
    | {
        message?: T;
        id?: T;
      };
  marqueeNeighborhoods?:
    | T
    | {
        name?: T;
        id?: T;
      };
  marqueeServices?:
    | T
    | {
        name?: T;
        id?: T;
      };
  aggregateRating?: T;
  reviewCount?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing_select".
 */
export interface PricingSelect<T extends boolean = true> {
  tableRows?:
    | T
    | {
        service?: T;
        bookingFee?: T;
        rate?: T;
        id?: T;
      };
  rolePricing?:
    | T
    | {
        role?: T;
        low?: T;
        high?: T;
        period?: T;
        note?: T;
        details?: T;
        popular?: T;
        id?: T;
      };
  feeBreakdown?:
    | T
    | {
        label?: T;
        value?: T;
        type?: T;
        id?: T;
      };
  lastUpdated?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coverage_select".
 */
export interface CoverageSelect<T extends boolean = true> {
  location?:
    | T
    | {
        regionLabel?: T;
        centerLat?: T;
        centerLng?: T;
        zoom?: T;
      };
  section?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        subtitle?: T;
      };
  neighborhoods?:
    | T
    | {
        name?: T;
        workers?: T;
        latitude?: T;
        longitude?: T;
        popularServices?:
          | T
          | {
              service?: T;
              id?: T;
            };
        id?: T;
      };
  totalWorkers?: T;
  avgMatchHours?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "marketing_select".
 */
export interface MarketingSelect<T extends boolean = true> {
  vetting?:
    | T
    | {
        title?: T;
        passRate?: T;
        steps?:
          | T
          | {
              icon?: T;
              title?: T;
              description?: T;
              isFinal?: T;
              id?: T;
            };
      };
  hireSteps?:
    | T
    | {
        title?: T;
        description?: T;
        ctaText?: T;
        ctaHref?: T;
        steps?:
          | T
          | {
              number?: T;
              title?: T;
              description?: T;
              stickyTop?: T;
              isFinal?: T;
              id?: T;
            };
      };
  comparison?:
    | T
    | {
        title?: T;
        columns?:
          | T
          | {
              label?: T;
              note?: T;
              variant?: T;
              id?: T;
            };
      };
  appCta?:
    | T
    | {
        title?: T;
        description?: T;
        appStoreUrl?: T;
        playStoreUrl?: T;
        image?: T;
      };
  matchForm?:
    | T
    | {
        title?: T;
        description?: T;
        benefits?:
          | T
          | {
              text?: T;
              id?: T;
            };
        serviceOptions?:
          | T
          | {
              label?: T;
              id?: T;
            };
        successMessage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  heroTitle?: T;
  heroImage?: T;
  originStory?: T;
  bodyStory?: T;
  storyImage?: T;
  mission?: T;
  vision?: T;
  values?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  impactStats?:
    | T
    | {
        value?: T;
        suffix?: T;
        label?: T;
        color?: T;
        id?: T;
      };
  ctaTitle?: T;
  ctaDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page_select".
 */
export interface ContactPageSelect<T extends boolean = true> {
  heroTitle?: T;
  heroDescription?: T;
  intents?:
    | T
    | {
        id?: T;
        icon?: T;
        title?: T;
        summary?: T;
        bestChannel?: T;
        responseTime?: T;
        actionLabel?: T;
        actionHref?: T;
        includeWhenContacting?:
          | T
          | {
              item?: T;
              id?: T;
            };
      };
  slas?:
    | T
    | {
        label?: T;
        value?: T;
        detail?: T;
        id?: T;
      };
  disputeSteps?:
    | T
    | {
        step?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  refundRules?:
    | T
    | {
        scenario?: T;
        outcome?: T;
        id?: T;
      };
  inquiryTypes?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  selfServiceLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal_select".
 */
export interface LegalSelect<T extends boolean = true> {
  terms?:
    | T
    | {
        updated?: T;
        description?: T;
        sections?:
          | T
          | {
              id?: T;
              title?: T;
              paragraphs?:
                | T
                | {
                    paragraph?: T;
                    id?: T;
                  };
              list?:
                | T
                | {
                    item?: T;
                    id?: T;
                  };
            };
      };
  privacy?:
    | T
    | {
        updated?: T;
        description?: T;
        sections?:
          | T
          | {
              id?: T;
              title?: T;
              paragraphs?:
                | T
                | {
                    paragraph?: T;
                    id?: T;
                  };
              list?:
                | T
                | {
                    item?: T;
                    id?: T;
                  };
            };
      };
  disclaimer?:
    | T
    | {
        updated?: T;
        description?: T;
        sections?:
          | T
          | {
              id?: T;
              title?: T;
              paragraphs?:
                | T
                | {
                    paragraph?: T;
                    id?: T;
                  };
              list?:
                | T
                | {
                    item?: T;
                    id?: T;
                  };
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}